const express = require('express');
const router = express.Router();
const vendorService = require('../services/vendorService');
const authMiddleware = require('../middleware/authMiddleware');
const upload = require('../middleware/uploadMiddleware');

/**
 * Vendor Routes
 * Handles vendor profile management and retrieval.
 * Base URL: /api/vendors
 */

/**
 * @route   GET /api/vendors/search
 * @desc    Search for vendors
 * @access  Public
 */
router.get('/search', async (req, res, next) => {
    try {
        const vendors = await vendorService.searchVendors(req.query);
        res.json(vendors);
    } catch (error) {
        next(error);
    }
});

/**
 * @route   GET /api/vendors
 * @desc    Get all vendor profiles
 * @access  Public
 */
router.get('/', async (req, res, next) => {
    try {
        const vendors = await vendorService.getAllVendors();
        res.json(vendors);
    } catch (error) {
        next(error);
    }
});

/**
 * @route   GET /api/vendors/profile
 * @desc    Get current user's vendor profile
 * @access  Private
 */
router.get('/profile', authMiddleware.protect, async (req, res, next) => {
    try {
        const profile = await vendorService.getProfile(req.user._id);
        res.json(profile);
    } catch (error) {
        next(error);
    }
});

/**
 * @route   POST /api/vendors/profile
 * @desc    Create or update vendor profile
 * @access  Private
 */
router.post('/profile', authMiddleware.protect, async (req, res, next) => {
    try {
        const profile = await vendorService.createOrUpdateProfile(req.user._id, req.body);
        res.json(profile);
    } catch (error) {
        next(error);
    }
});

/**
 * @route   POST /api/vendors/upload
 * @desc    Upload an image
 * @access  Private (Vendor only)
 */
// This route uses multiple middleware:
// 1. authMiddleware.protect: Ensures user is logged in
// 2. authMiddleware.vendor: Ensures user is a vendor
// 3. upload.single('image'): Handles the actual file upload (saves to /uploads)
router.post('/upload', authMiddleware.protect, authMiddleware.vendor, upload.single('image'), (req, res) => {
    try {
        // req.file contains information about the uploaded file
        if (!req.file) {
            return res.status(400).json({ message: 'No file uploaded' });
        }

        // Construct the URL where the image can be accessed
        // req.protocol = http or https
        // req.get('host') = localhost:5000
        // req.file.filename = the unique name generated by multer
        const imageUrl = `${req.protocol}://${req.get('host')}/uploads/${req.file.filename}`;

        // Return the URL to the frontend so it can be displayed or saved
        res.json({ imageUrl });
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
});

/**
 * @route   POST /api/vendors/portfolio
 * @desc    Add an image to vendor portfolio
 * @access  Private
 */
router.post('/portfolio', authMiddleware.protect, async (req, res, next) => {
    try {
        const { imageUrl } = req.body;
        const profile = await vendorService.addPortfolioImage(req.user._id, imageUrl);
        res.json(profile);
    } catch (error) {
        next(error);
    }
});

module.exports = router;
